### ISSUE TITLE
"cargo-maelstrom integration_test few_tests" fails occasionally

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#280]
I managed to get it while I was running all the tests at once. Just running this test in a loop doesn't trigger it.

This is the output:
```
stderr: thread 'tokio-runtime-worker' panicked at /home/neal/maelstrom/crates/cargo-maelstrom/src/visitor.rs:265:22:
stderr: called `Option::unwrap()` on a `None` value
stderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
stderr: thread 'few_tests' panicked at crates/cargo-maelstrom/tests/integration_test.rs:116:5:
stderr: project bar............................OK   0.036s
stderr:
stderr: ================== Test Summary ==================
stderr: Successful Tests:         2
stderr: Failed Tests    :         0
```

Looking at the code:
```rust
105 #[test]
106 fn few_tests() {
107     let contents = do_cargo_maelstrom_test(
108         "
109         #[test]
110         fn foo() {}
111
112         #[test]
113         fn bar() {}
114         ",
115     );
116     assert!(
117         contents.contains("project foo............................OK"),
118         "{contents}"
119     );
120     assert!(
121         contents.contains("project bar............................OK"),
122         "{contents}"
123     );
124     assert!(
125         contents.contains("Successful Tests:         2"),
126         "{contents}"
127     );
128     assert!(
129         contents.contains("Failed Tests    :         0"),
130         "{contents}"
131     );
132 }
```

So it looks like the test ran, but its output got eaten.

**Comment by nfachan** [comment]
I can pretty consistently get it to fail with:
```bash
while cargo maelstrom; do; done
```

**Comment by nfachan** [comment]
Seems to be fixed with most recent changes pulled.
